name: Deploy Contracts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy to SKALE
        env:
          PRIVATE_KEY: ${{ secrets.SKALE_PRIVATE_KEY }}
          RPC_URL: ${{ secrets.SKALE_RPC_URL }}
        run: npx hardhat run scripts/deploy.js --network skale
